services:
  blocklist:
    container_name: Blocklist_Generator
    restart: unless-stopped
    build: .
    env_file: ".env"
    volumes:
      - NAS:/NAS
      - /etc/localtime:/etc/localtime:ro

volumes:
  NAS:
    external: true