services:
  blocklist:
    container_name: Blocklist_Generator
    restart: unless-stopped
    build: .
    environment:
      - OutputPath=${OutputPath}
    volumes:
      - NAS:/NAS

volumes:
  NAS:
    external: true