from requests import get
from os import environ
import schedule
import time

def grab_blocklists():
    with open('blocklists.txt') as blocklistsFile:
        blocklists = [x for x in blocklistsFile.read().splitlines() if x.startswith('http')]

    URLs = set()

    for list in blocklists:
        try:
            response = get(list)

            if response.ok:
                print(f"Downloaded {list}")
                tmpURLs = [y.decode("utf-8").split(" ")[-1].split("	")[-1].split("/")[0] for y in response.content.splitlines() if len(y.decode("utf-8")) > 0 and y.decode("utf-8")[0].isalpha() and y.decode("utf-8").strip()]
                URLs.update(tmpURLs)
            else:
                print(f"Error downloading list: {response.status_code}")
        except:
            print(f"Error downloading list")

    with open(environ['OutputPath'], 'w') as outFile:
        outFile.write(f"# This file is automatically generated by https://github.com/Mnky313/BlocklistGenerator/ at {time.ctime()}\n")
        for URL in URLs:
            outFile.write(f"{URL}\n")

schedule.every().day.at("02:00").do(grab_blocklists)

while True:
    schedule.run_pending()
    time.sleep(60)